### ISSUE TITLE
Fetching Elbas is broken

### ISSUE THREAD

**Issue by kipe** [kipe/nordpool#12]
Fetching Elbas-data is currently broken, because of addition (X) and (I) to the product names. Need to first find out what they mean, before determining if the data format should be changed, only one of the prices should be included or what...

**Comment by kipe** [comment]
At the same time, the format of Elbas data should be changed. It would be more logical to group the data first by product type (PH, 2H, 4H, DON, DB, QH, etc). Then give the timebased values for AVG, volume etc.

With this change, the (I) and (X) in the product name don't really matter.

**Comment by kipe** [comment]
Well, this is even more broken now. Willing to accept PRs, otherwise I'm removing Elbas completely.

**Comment by silpol** [comment]
@kipe it's time to remove Elbas branch altogether

**Comment by kipe** [comment]
Version 0.4.3 was just released, Elbas removed completely (at least for now).
