### ISSUE TITLE
Current day prices and day ahead prices

### ISSUE THREAD

**Issue by PatrikPatrik2** [kipe/nordpool#14]
I would need both todays prices and tomorrows prices - can I get todays prices by using something like:
pprint(prices_spot.hourly(end_date=['2020-11-20'],areas=['SE3']))

I tried several versions but I only got errors

**Comment by sebchalmers** [comment]
Same here, did you find a fix?

**Comment by sebchalmers** [comment]
Ok, e.g. the command:

elspot.Prices().hourly(areas=['Tr.heim'],end_date='2020-12-09')

works (assuming '2020-12-09' is todays date)
