### ISSUE TITLE
'value': inf

### ISSUE THREAD

**Issue by cultpenguin** [kipe/nordpool#22]
When I run the example 
`
     pprint(prices_spot.hourly(areas=['DK1']))
`
I get only 'nan' values for the price. See: 

      {'areas': {'DK1': {'Average': inf,
                   'Max': inf,
                   'Min': inf,
                   'Off-peak 1': inf,
                   'Off-peak 2': inf,
                   'Peak': inf,
                   'values': [{'end': datetime.datetime(2021, 10, 28, 23, 0, tzinfo=<UTC>),
                               'start': datetime.datetime(2021, 10, 28, 22, 0, tzinfo=<UTC>),
                               'value': inf},
                              {'end': datetime.datetime(2021, 10, 29, 0, 0, tzinfo=<UTC>),
                               'start': datetime.datetime(2021, 10, 28, 23, 0, tzinfo=<UTC>),
                               'value': inf},

Is this expected or a bug?

Have a nice day
- Th9mnas

**Comment by karlbjoe** [comment]
I had the same problem. I think you get inf if you ask for the day-ahead prices before 13:00 CET, since they are only available after that time.

**Comment by kipe** [comment]
Yes, exactly. If you're requesting the values before they're published, they're reported as infinite values.
