### ISSUE TITLE
Specifying starting time

### ISSUE THREAD

**Issue by jsk1360** [kipe/nordpool#25]
Is there any way to get data for a whole day? Currently, when I specify a date, the first price value is for the current hour and does not go from midnight to midnight to cover a whole day, unless the code runs from midnight to 1 AM.

**Comment by kaistian** [comment]
I can't confirm this behavior, when I set a date, I get data for the whole day.

**Comment by jsk1360** [comment]
This issue is resolved, but I couldn't delete the thread or mark it as resolved. It was about the one-hour time difference between Sweden and Finland. I handled it locally after fetching the data.
