### ISSUE TITLE
Nordpool day-ahead prices in a "," separated string/char[] array ?

### ISSUE THREAD

**Issue by arosandreas** [kipe/nordpool#29]
Hi,
would it be possible to get Nordpool day-ahead prices in a "," separated string/char[] array ?
Example : day. ahead-prices
00-01 10
01-02 12
...
23..24 15
--> String myString="10,12,.....,15"

myString will then be sent from Python to my Blynk server, using Blynk API.
https://{server_address}/external/api/update?token={token}&v4=myString

best regards
andreas

**Comment by kipe** [comment]
That's simple enough to do just by writing couple of lines code, not this projects task -> closed.
