### ISSUE TITLE
In HA, make state of freely choosen price value

### ISSUE THREAD

**Issue by Nordavinda** [kipe/nordpool#30]
If you want to pick out the cheapest hours of the day it would be convenient to make å state out of e.g. the 5th cheapest hour of the day to make sure you use electricity for a full 4 hours, but not more, and not less.
With the cutoff-value as today, sometimes when the day-curves are flat you want get your templates to trigger that day and you risk to get a cold morning shower.
Any ideas for how to make this?

**Comment by kipe** [comment]
Not related to this project -> closed.
