### ISSUE TITLE
API going EOL?

### ISSUE THREAD

**Issue by johanschag** [kipe/nordpool#35]
I've been using this software for 2 years now and it's awesome, but since this summer my software hangs after 5 days. I noticed that Nord Pool will gradually shut down their V1 API. I'm not sure, but it could be that only 100 API calls are allowed and then access is denied. Any plans to change to V2 API?

**Comment by flopp999** [comment]
I am not sure this package is using the API. To be able to use the API you need to have an agreement.
I think this package is only fetching JSON data.

**Comment by kipe** [comment]
Yeah, this library isn't using any official APIs. It essentiallly fetches exactly the same information from the same endpoints as their public facing website.
