### ISSUE TITLE
0.4.0 releases lack setup.py

### ISSUE THREAD

**Issue by sander-visser** [kipe/nordpool#44]
python3 -m pip install -U git+https://github.com/kipe/nordpool.git
Collecting git+https://github.com/kipe/nordpool.git
  Cloning https://github.com/kipe/nordpool.git to /tmp/pip-2zlyfyzt-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-2zlyfyzt-build/setup.py'

**Comment by kipe** [comment]
Oh, actually need to update the README.md, as the package is available in PyPi and now handled via poetry.

**Comment by kipe** [comment]
Actually the install seems to work fine with a reasonably recent pip. Didn't know you're still running Python 3.6 -> not supported.
