### ISSUE TITLE
elspot.Prices() stopped working 15.10.24

### ISSUE THREAD

**Issue by ismoo1** [kipe/nordpool#46]
Firstly, thanks for excellent library helping for years already, until today I got stuck...

Since yesterday function seems to return "no response", I updated latest 0.4.1 library but did not help. 
From code I tried url  manually (API_URL = "https://dataportal-api.nordpoolgroup.com/api") manually but failed:
This dataportal-api.nordpoolgroup.com page can’t be found.

Is this common problem, and can it be solved? e.g. this link looks to work still:
https://elspotcontrol.netlify.app/spotprices-v01-FI.json

To me looks other changes taken place as well based on google, 

Nord Pool
https://www.nordpoolgroup.com › ...

data12/Dayahead/Area-Prices/SE/Hourly/&prev=search&pto=aue)
6 päivää sitten — This page will be deactivated on 14.10.2024. Y

**Comment by Landbogarden01** [comment]
Same here!

**Comment by kipe** [comment]
This is already handled and fixed via 0.4.1.
The thing is that the library by default fetches the prices for tomorrow and as the prices aren't yet available, there's no response.

As for the opening the URL's manually, the URL needs to be full, including the whole path, all the variables etc.

**Comment by ismoo1** [comment]
Great, thanks for quick resolution, so by afternoon then should be all good

**Comment by kipe** [comment]
I've now updated both the readme and example to note about None -response.
