### ISSUE TITLE
Question about reponse.

### ISSUE THREAD

**Issue by oppsig** [kipe/nordpool#5]
What does the last two digits **22, 0** in the response mean? 
```
{'areas': {'FI': {'values': [{'end': datetime.datetime(2018, 8, 17, 22, 0, tzinfo=<UTC>),
                                  'start': datetime.datetime(2018, 8, 16, 22, 0, tzinfo=<UTC>),
                                  'value': inf},
                                 {'end': datetime.datetime(2018, 8, 16, 22, 0, tzinfo=<UTC>),
                                  'start': datetime.datetime(2018, 8, 15, 22, 0, tzinfo=<UTC>),
                                  'value': 50.09},
```

**Comment by jpalo** [comment]
I guess it only indicates time. Should be 00, 00 so midnight, but some conversion somewhere messes it up and it becomes 22, 0, i.e., 10 PM. If I remember correctly the original data from Nordpool also has it like this.

**Comment by kipe** [comment]
It is time, and no, conversion doesn't mess it up. It's just converted to UTC timezone and timezone information is added to the timestamp.
Nordpool uses CET / CEST for their times and publishes prices for 00-23 in that timezone -> offset of 1 or 2 hours in UTC, depending on daylight savings.
