### ISSUE TITLE
page not found

### ISSUE THREAD

**Issue by gustaj1900** [kipe/nordpool#51]
Hi,

I get page not found when using the nordpool elbas, with the following response:

<body>
    <div class="container">
        <h1>Page Not Found</h1>
        <p>The page you're looking for doesn't exist.</p>
        <p>We hope you'll find what you need on our website: <a href="https://www.nordpoolgroup.com">nordpoolgroup.com</a></p>
        <p>If you're searching for Market Data, you can find it on our <a href="https://data.nordpoolgroup.com/">Data Portal</a>.</p>
    </div>

Is not Nordpool API gone, or has something changed? I cannot find any documentation around the API used by elbas

**Comment by silpol** [comment]
Elbas fetching is broken since 2020 - see issue #12

**Comment by gustaj1900** [comment]
Really, but it worked fine up until a few weeks ago?

**Comment by kipe** [comment]
@gustaj1900 Are you speaking really of Elbas, not Elspot?

**Comment by kipe** [comment]
Version 0.4.3 was just released, Elbas removed completely (at least for now).
