### ISSUE TITLE
Install the latest version

### ISSUE THREAD

**Issue by jamisi** [kipe/nordpool#52]
Hi,
The command pip install nordpool installs the version 0.3.3.
I removed package (pip uninstall nordpool), but still it is installing the old version. With that there is jsondecode errors.

**Comment by Kostoprav19** [comment]
Hi! First you need to update python to at least version 3.10. Then you will be able to update nordpool to 0.4.2

**Comment by kipe** [comment]
Version 0.4.3 was just released, with minimum Python version being 3.9.
