### ISSUE TITLE
Not working - parse errors

### ISSUE THREAD

**Issue by Patrick356356** [kipe/nordpool#53]
Hi,
I have been using your code for long (thank you for that!!!) and it worked just fine until two weeks ago. I then saw you did some updates two weeks ago and therefore updated but I still don't get it to work. I must admit I'm not that good at Python and have problems to trace the problem in the code. When running your simple test code I get parsing errors, please see attached picture. What are your thoughts? The Python version running on current raspberry pi os is 3.9.2.
Kind regards
Patrick
![Nordpool error](https://github.com/user-attachments/assets/db490564-171f-4e22-b7a6-372006a11495)

**Comment by jbr007** [comment]
Tried this code
#!/usr/bin/env python

# Import library for fetching Elspot data
from nordpool import elspot
from pprint import pprint

# Initialize class for fetching Elspot prices
prices_spot = elspot.Prices()

# Fetch hourly Elspot prices for Finland and print the resulting dictionary.
# If the prices are reported as None, it means that the prices fetched aren't yet available.
# The library by default tries to fetch prices for tomorrow and they're released ~13:00 Swedish time.
pprint(prices_spot.hourly(areas=["FI"]))

in file price.py

Then python3 price.py
Got as above
Traceback (most recent call last):
  File "price.py", line 13, in <module>
    pprint(prices_spot.hourly(areas=["FI"]))
  File "/usr/local/lib/python3.5/dist-packages/nordpool/elspot.py", line 132, in hourly
    return self.fetch(self.HOURLY, end_date, areas)
  File "/usr/local/lib/python3.5/dist-packages/nordpool/elspot.py", line 128, in fetch
    return self._parse_json(self._fetch_json(data_type, end_date), areas)
  File "/usr/local/lib/python3.5/dist-packages/nordpool/elspot.py", line 104, in _fetch_json
    return r.json()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Kostoprav19** [comment]
Hi! Please make sure you have updated to version 0.4.2, but first you need to update python to at least version 3.10

**Comment by kipe** [comment]
Version 0.4.3 was just released, with minimum Python version being 3.9.
